<?php
/***************************************************************************
*
*   Copyright(c) Leaf Linux and Jeff V. Merkey 1997-2022.
*   All rights reserved.
*
*   Leaf PHP Web Console
*
**************************************************************************/

// Memcached Return Codes

$memcache_retcodes=array(
   "00" => "MEMCACHED_SUCCESS",
   "01" => "MEMCACHED_FAILURE",
   "02" => "MEMCACHED_HOST_LOOKUP_FAILURE", // getaddrinfo() and getnameinfo() only
   "03" => "MEMCACHED_CONNECTION_FAILURE",
   "04" => "MEMCACHED_CONNECTION_BIND_FAILURE", // DEPRECATED see MEMCACHED_HOST_LOOKUP_FAILURE
   "05" => "MEMCACHED_WRITE_FAILURE",
   "06" => "MEMCACHED_READ_FAILURE",
   "07" => "MEMCACHED_UNKNOWN_READ_FAILURE",
   "08" => "MEMCACHED_PROTOCOL_ERROR",
   "09" => "MEMCACHED_CLIENT_ERROR",
   "10" => "MEMCACHED_SERVER_ERROR", // Server returns "SERVER_ERROR"
   "11" => "MEMCACHED_ERROR", // Server returns "ERROR"
   "12" => "MEMCACHED_DATA_EXISTS",
   "13" => "MEMCACHED_DATA_DOES_NOT_EXIST",
   "14" => "MEMCACHED_NOTSTORED",
   "15" => "MEMCACHED_STORED",
   "16" => "MEMCACHED_NOTFOUND",
   "17" => "MEMCACHED_MEMORY_ALLOCATION_FAILURE",
   "18" => "MEMCACHED_PARTIAL_READ",
   "19" => "MEMCACHED_SOME_ERRORS",
   "20" => "MEMCACHED_NO_SERVERS",
   "21" => "MEMCACHED_END",
   "22" => "MEMCACHED_DELETED",
   "23" => "MEMCACHED_VALUE",
   "24" => "MEMCACHED_STAT",
   "25" => "MEMCACHED_ITEM",
   "26" => "MEMCACHED_ERRNO",
   "27" => "MEMCACHED_FAIL_UNIX_SOCKET", // DEPRECATED
   "28" => "MEMCACHED_NOT_SUPPORTED",
   "29" => "MEMCACHED_NO_KEY_PROVIDED", // Deprecated. Use MEMCACHED_BAD_KEY_PROVIDED! 
   "30" => "MEMCACHED_FETCH_NOTFINISHED",
   "31" => "MEMCACHED_TIMEOUT",
   "32" => "MEMCACHED_BUFFERED",
   "33" => "MEMCACHED_BAD_KEY_PROVIDED",
   "34" => "MEMCACHED_INVALID_HOST_PROTOCOL",
   "35" => "MEMCACHED_SERVER_MARKED_DEAD",
   "36" => "MEMCACHED_UNKNOWN_STAT_KEY",
   "37" => "MEMCACHED_E2BIG",
   "38" => "MEMCACHED_INVALID_ARGUMENTS",
   "39" => "MEMCACHED_KEY_TOO_BIG",
   "40" => "MEMCACHED_AUTH_PROBLEM",
   "41" => "MEMCACHED_AUTH_FAILURE",
   "42" => "MEMCACHED_AUTH_CONTINUE",
   "43" => "MEMCACHED_PARSE_ERROR",
   "44" => "MEMCACHED_PARSE_USER_ERROR",
   "45" => "MEMCACHED_DEPRECATED",
   "46" => "MEMCACHED_IN_PROGRESS",
   "47" => "MEMCACHED_SERVER_TEMPORARILY_DISABLED",
   "48" => "MEMCACHED_SERVER_MEMORY_ALLOCATION_FAILURE",
   "49" => "MEMCACHED_MAXIMUM_RETURN", // Always add new error code before 
);

$secure_hash_algo = array(
    "md2",
    "md4",
    "md5",
    "sha1",
    "sha224",
    "sha256",
    "sha384",
    "sha512/224",
    "sha512/256",
    "sha512",
    "sha3-224",
    "sha3-256",
    "sha3-384",
    "sha3-512",
    "ripemd128",
    "ripemd160",
    "ripemd256",
    "ripemd320",
    "whirlpool",
    "tiger128,3",
    "tiger160,3",
    "tiger192,3",
    "tiger128,4",
    "tiger160,4",
    "tiger192,4",
    "snefru",
    "snefru256",
    "gost",
    "gost-crypto",
    "adler32",
    "crc32",
    "crc32b",
    "crc32c",
    "fnv132",
    "fnv1a32",
    "fnv164",
    "fnv1a64",
    "joaat",
    "murmur3a",
    "murmur3c",
    "murmur3f",
    "xxh32",
    "xxh64",
    "xxh3",
    "xxh128",
    "haval128,3",
    "haval160,3",
    "haval192,3",
    "haval224,3",
    "haval256,3",
    "haval128,4",
    "haval160,4",
    "haval192,4",
    "haval224,4",
    "haval256,4",
    "haval128,5",
    "haval160,5",
    "haval192,5",
    "haval224,5",
    "haval256,5",
);


$languages =  array(
   "ab" => "Abkhazian",
   "aa" => "Afar",
   "af" => "Afrikaans",
   "ak" => "Akan",
   "sq" => "Albanian",
   "am" => "Amharic",
   "ar" => "Arabic",
   "an" => "Aragonese",
   "hy" => "Armenian",
   "as" => "Assamese",
   "av" => "Avaric",
   "ae" => "Avestan",
   "ay" => "Aymara",
   "az" => "Azerbaijani",
   "bm" => "Bambara",
   "ba" => "Bashkir",
   "eu" => "Basque",
   "be" => "Belarusian",
   "bn" => "Bengali (Bangla)",
   "bh" => "Bihari",
   "bi" => "Bislama",
   "bs" => "Bosnian",
   "br" => "Breton",
   "bg" => "Bulgarian",
   "my" => "Burmese",
   "ca" => "Catalan",
   "ch" => "Chamorro",
   "ce" => "Chechen",
   "ny" => "Chichewa, Chewa, Nyanja",
   "zh" => "Chinese",
   "zh-Hans" => "Chinese (Simplified)",
   "zh-Hant" => "Chinese (Traditional)",
   "cv" => "Chuvash",
   "kw" => "Cornish",
   "co" => "Corsican",
   "cr" => "Cree",
   "hr" => "Croatian",
   "cs" => "Czech",
   "da" => "Danish",
   "dv" => "Divehi, Dhivehi, Maldivian",
   "nl" => "Dutch",
   "dz" => "Dzongkha",
   "en" => "English",
   "eo" => "Esperanto",
   "et" => "Estonian",
   "ee" => "Ewe",
   "fo" => "Faroese",
   "fj" => "Fijian",
   "fi" => "Finnish",
   "fr" => "French",
   "ff" => "Fula, Fulah, Pulaar, Pular",
   "gl" => "Galician",
   "gd" => "Gaelic (Scottish)",
   "gv" => "Gaelic (Manx)",
   "ka" => "Georgian",
   "de" => "German",
   "el" => "Greek",
   "kl" => "Greenlandic",
   "gn" => "Guarani",
   "gu" => "Gujarati",
   "ht" => "Haitian Creole",
   "ha" => "Hausa",
   "he" => "Hebrew",
   "hz" => "Herero",
   "hi" => "Hindi",
   "ho" => "Hiri Motu",
   "hu" => "Hungarian",
   "is" => "Icelandic",
   "io" => "Ido",
   "ig" => "Igbo",
   "id" => "Indonesian (id)",
   "in" => "Indonesian (in)",
   "ia" => "Interlingua",
   "ie" => "Interlingue",
   "iu" => "Inuktitut",
   "ik" => "Inupiak",
   "ga" => "Irish",
   "it" => "Italian",
   "ja" => "Japanese",
   "jv" => "Javanese",
   "kl" => "Kalaallisut, Greenlandic",
   "kn" => "Kannada",
   "kr" => "Kanuri",
   "ks" => "Kashmiri",
   "kk" => "Kazakh",
   "km" => "Khmer",
   "ki" => "Kikuyu",
   "rw" => "Kinyarwanda (Rwanda)",
   "rn" => "Kirundi",
   "ky" => "Kyrgyz",
   "kv" => "Komi",
   "kg" => "Kongo",
   "ko" => "Korean",
   "ku" => "Kurdish",
   "kj" => "Kwanyama",
   "lo" => "Lao",
   "la" => "Latin",
   "lv" => "Latvian (Lettish)",
   "li" => "Limburgish (Limburger)",
   "ln" => "Lingala",
   "lt" => "Lithuanian",
   "lu" => "Luga-Katanga",
   "lg" => "Luganda, Ganda",
   "lb" => "Luxembourgish",
   "gv" => "Manx",
   "mk" => "Macedonian",
   "mg" => "Malagasy",
   "ms" => "Malay",
   "ml" => "Malayalam",
   "mt" => "Maltese",
   "mi" => "Maori",
   "mr" => "Marathi",
   "mh" => "Marshallese",
   "mo" => "Moldavian",
   "mn" => "Mongolian",
   "na" => "Nauru",
   "nv" => "Navajo",
   "ng" => "Ndonga",
   "nd" => "Northern Ndebele",
   "ne" => "Nepali",
   "no" => "Norwegian",
   "nb" => "Norwegian bokmål",
   "nn" => "Norwegian nynorsk",
   "ii" => "Nuosu",
   "oc" => "Occitan",
   "oj" => "Ojibwe",
   "cu" => "Old Church Slavonic",
   "cu" => "Old Bulgarian",
   "or" => "Oriya",
   "om" => "Oromo (Afaan Oromo)",
   "os" => "Ossetian",
   "pi" => "Pāli",
   "ps" => "Pashto, Pushto",
   "fa" => "Persian (Farsi)",
   "pl" => "Polish",
   "pt" => "Portuguese",
   "pa" => "Punjabi (Eastern)",
   "qu" => "Quechua",
   "rm" => "Romansh",
   "ro" => "Romanian",
   "ru" => "Russian",
   "se" => "Sami",
   "sm" => "Samoan",
   "sg" => "Sango",
   "sa" => "Sanskrit",
   "sr" => "Serbian",
   "sh" => "Serbo-Croatian",
   "st" => "Sesotho",
   "tn" => "Setswana",
   "sn" => "Shona",
   "ii" => "Sichuan Yi",
   "sd" => "Sindhi",
   "si" => "Sinhalese",
   "ss" => "Siswati",
   "sk" => "Slovak",
   "sl" => "Slovenian",
   "so" => "Somali",
   "nr" => "Southern Ndebele",
   "es" => "Spanish",
   "su" => "Sundanese",
   "sw" => "Swahili (Kiswahili)",
   "ss" => "Swati",
   "sv" => "Swedish",
   "tl" => "Tagalog",
   "ty" => "Tahitian",
   "tg" => "Tajik",
   "ta" => "Tamil",
   "tt" => "Tatar",
   "te" => "Telugu",
   "th" => "Thai",
   "bo" => "Tibetan",
   "ti" => "Tigrinya",
   "to" => "Tonga",
   "ts" => "Tsonga",
   "tr" => "Turkish",
   "tk" => "Turkmen",
   "tw" => "Twi",
   "ug" => "Uyghur",
   "uk" => "Ukrainian",
   "ur" => "Urdu",
   "uz" => "Uzbek",
   "ve" => "Venda",
   "vi" => "Vietnamese",
   "vo" => "Volapük",
   "wa" => "Wallon",
   "cy" => "Welsh",
   "wo" => "Wolof",
   "fy" => "Western Frisian",
   "xh" => "Xhosa",
   "yi" => "Yiddish (yi)",
   "ji" => "Yiddish (ji)",
   "yo" => "Yoruba",
   "za" => "Zhuang, Chuang",
   "zu" => "Zulu",
);

$countries = array(
   "US" => "United States of America",
   "AF" => "Afghanistan",
   "AL" => "Albania",
   "DZ" => "Algeria",
   "AS" => "American Samoa",
   "AD" => "Andorra",
   "AG" => "Angola",
   "AI" => "Anguilla",
   "AG" => "Antigua &amp; Barbuda",
   "AR" => "Argentina",
   "AA" => "Armenia",
   "AW" => "Aruba",
   "AU" => "Australia",
   "AT" => "Austria",
   "AZ" => "Azerbaijan",
   "BS" => "Bahamas",
   "BH" => "Bahrain",
   "BD" => "Bangladesh",
   "BB" => "Barbados",
   "BY" => "Belarus",
   "BE" => "Belgium",
   "BZ" => "Belize",
   "BJ" => "Benin",
   "BM" => "Bermuda",
   "BT" => "Bhutan",
   "BO" => "Bolivia",
   "BL" => "Bonaire",
   "BA" => "Bosnia &amp; Herzegovina",
   "BW" => "Botswana",
   "BR" => "Brazil",
   "BC" => "British Indian Ocean Ter",
   "BN" => "Brunei",
   "BG" => "Bulgaria",
   "BF" => "Burkina Faso",
   "BI" => "Burundi",
   "KH" => "Cambodia",
   "CM" => "Cameroon",
   "CA" => "Canada",
   "IC" => "Canary Islands",
   "CV" => "Cape Verde",
   "KY" => "Cayman Islands",
   "CF" => "Central African Republic",
   "TD" => "Chad",
   "CD" => "Channel Islands",
   "CL" => "Chile",
   "CN" => "China",
   "CI" => "Christmas Island",
   "CS" => "Cocos Island",
   "CO" => "Colombia",
   "CC" => "Comoros",
   "CG" => "Congo",
   "CK" => "Cook Islands",
   "CR" => "Costa Rica",
   "CT" => "Cote D'Ivoire",
   "HR" => "Croatia",
   "CU" => "Cuba",
   "CB" => "Curacao",
   "CY" => "Cyprus",
   "CZ" => "Czech Republic",
   "DK" => "Denmark",
   "DJ" => "Djibouti",
   "DM" => "Dominica",
   "DO" => "Dominican Republic",
   "TM" => "East Timor",
   "EC" => "Ecuador",
   "EG" => "Egypt",
   "SV" => "El Salvador",
   "GQ" => "Equatorial Guinea",
   "ER" => "Eritrea",
   "EE" => "Estonia",
   "ET" => "Ethiopia",
   "FA" => "Falkland Islands",
   "FO" => "Faroe Islands",
   "FJ" => "Fiji",
   "FI" => "Finland",
   "FR" => "France",
   "GF" => "French Guiana",
   "PF" => "French Polynesia",
   "FS" => "French Southern Ter",
   "GA" => "Gabon",
   "GM" => "Gambia",
   "GE" => "Georgia",
   "DE" => "Germany",
   "GH" => "Ghana",
   "GI" => "Gibraltar",
   "GB" => "Great Britain",
   "GR" => "Greece",
   "GL" => "Greenland",
   "GD" => "Grenada",
   "GP" => "Guadeloupe",
   "GU" => "Guam",
   "GT" => "Guatemala",
   "GN" => "Guinea",
   "GY" => "Guyana",
   "HT" => "Haiti",
   "HW" => "Hawaii",
   "HN" => "Honduras",
   "HK" => "Hong Kong",
   "HU" => "Hungary",
   "IS" => "Iceland",
   "IN" => "India",
   "ID" => "Indonesia",
   "IA" => "Iran",
   "IQ" => "Iraq",
   "IR" => "Ireland",
   "IM" => "Isle of Man",
   "IL" => "Israel",
   "IT" => "Italy",
   "JM" => "Jamaica",
   "JP" => "Japan",
   "JO" => "Jordan",
   "KZ" => "Kazakhstan",
   "KE" => "Kenya",
   "KI" => "Kiribati",
   "NK" => "Korea North",
   "KS" => "Korea South",
   "KW" => "Kuwait",
   "KG" => "Kyrgyzstan",
   "LA" => "Laos",
   "LV" => "Latvia",
   "LB" => "Lebanon",
   "LS" => "Lesotho",
   "LR" => "Liberia",
   "LY" => "Libya",
   "LI" => "Liechtenstein",
   "LT" => "Lithuania",
   "LU" => "Luxembourg",
   "MO" => "Macau",
   "MK" => "Macedonia",
   "MG" => "Madagascar",
   "MY" => "Malaysia",
   "MW" => "Malawi",
   "MV" => "Maldives",
   "ML" => "Mali",
   "MT" => "Malta",
   "MH" => "Marshall Islands",
   "MQ" => "Martinique",
   "MR" => "Mauritania",
   "MU" => "Mauritius",
   "ME" => "Mayotte",
   "MX" => "Mexico",
   "MI" => "Midway Islands",
   "MD" => "Moldova",
   "MC" => "Monaco",
   "MN" => "Mongolia",
   "MS" => "Montserrat",
   "MA" => "Morocco",
   "MZ" => "Mozambique",
   "MM" => "Myanmar",
   "NA" => "Nambia",
   "NU" => "Nauru",
   "NP" => "Nepal",
   "AN" => "Netherland Antilles",
   "NL" => "Netherlands (Holland, Europe)",
   "NV" => "Nevis",
   "NC" => "New Caledonia",
   "NZ" => "New Zealand",
   "NI" => "Nicaragua",
   "NE" => "Niger",
   "NG" => "Nigeria",
   "NW" => "Niue",
   "NF" => "Norfolk Island",
   "NO" => "Norway",
   "OM" => "Oman",
   "PK" => "Pakistan",
   "PW" => "Palau Island",
   "PS" => "Palestine",
   "PA" => "Panama",
   "PG" => "Papua New Guinea",
   "PY" => "Paraguay",
   "PE" => "Peru",
   "PH" => "Philippines",
   "PO" => "Pitcairn Island",
   "PL" => "Poland",
   "PT" => "Portugal",
   "PR" => "Puerto Rico",
   "QA" => "Qatar",
   "ME" => "Republic of Montenegro",
   "RS" => "Republic of Serbia",
   "RE" => "Reunion",
   "RO" => "Romania",
   "RU" => "Russia",
   "RW" => "Rwanda",
   "NT" => "St Barthelemy",
   "EU" => "St Eustatius",
   "HE" => "St Helena",
   "KN" => "St Kitts-Nevis",
   "LC" => "St Lucia",
   "MB" => "St Maarten",
   "PM" => "St Pierre &amp; Miquelon",
   "VC" => "St Vincent &amp; Grenadines",
   "SP" => "Saipan",
   "SO" => "Samoa",
   "AS" => "Samoa American",
   "SM" => "San Marino",
   "ST" => "Sao Tome &amp; Principe",
   "SA" => "Saudi Arabia",
   "SN" => "Senegal",
   "SC" => "Seychelles",
   "SL" => "Sierra Leone",
   "SG" => "Singapore",
   "SK" => "Slovakia",
   "SI" => "Slovenia",
   "SB" => "Solomon Islands",
   "OI" => "Somalia",
   "ZA" => "South Africa",
   "ES" => "Spain",
   "LK" => "Sri Lanka",
   "SD" => "Sudan",
   "SR" => "Suriname",
   "SZ" => "Swaziland",
   "SE" => "Sweden",
   "CH" => "Switzerland",
   "SY" => "Syria",
   "TA" => "Tahiti",
   "TW" => "Taiwan",
   "TJ" => "Tajikistan",
   "TZ" => "Tanzania",
   "TH" => "Thailand",
   "TG" => "Togo",
   "TK" => "Tokelau",
   "TO" => "Tonga",
   "TT" => "Trinidad &amp; Tobago",
   "TN" => "Tunisia",
   "TR" => "Turkey",
   "TU" => "Turkmenistan",
   "TC" => "Turks &amp; Caicos Is",
   "TV" => "Tuvalu",
   "UG" => "Uganda",
   "UA" => "Ukraine",
   "AE" => "United Arab Emirates",
   "GB" => "United Kingdom",
   "UY" => "Uruguay",
   "UZ" => "Uzbekistan",
   "VU" => "Vanuatu",
   "VS" => "Vatican City State",
   "VE" => "Venezuela",
   "VN" => "Vietnam",
   "VB" => "Virgin Islands (Brit)",
   "VA" => "Virgin Islands (USA)",
   "WK" => "Wake Island",
   "WF" => "Wallis &amp; Futana Is",
   "YE" => "Yemen",
   "ZR" => "Zaire",
   "ZM" => "Zambia",
   "ZW" => "Zimbabwe",
);

$states = array(
	"AL"=>"Alabama",
	"AK"=>"Alaska",
	"AB"=>"Alberta",
	"AZ"=>"Arizona",
	"AR"=>"Arkansas",
	"AS"=>"American Samoa",
	"BC"=>"British Columbia",
	"CA"=>"California",
	"CO"=>"Colorado",
	"CT"=>"Connecticut",
	"DC"=>"District of Columbia",
	"DE"=>"Delaware",
	"FL"=>"Florida",
	"GA"=>"Georgia",
	"GU"=>"Guam",
	"HI"=>"Hawaii",
	"ID"=>"Idaho",
	"IL"=>"Illinois",
	"IN"=>"Indiana",
	"IA"=>"Iowa",
	"KS"=>"Kansas",
	"KY"=>"Kentucky",
	"LA"=>"Louisiana",
	"ME"=>"Maine",
	"MD"=>"Maryland",
	"MA"=>"Massachusetts",
	"MI"=>"Michigan",
	"MB"=>"Manitoba",
	"MH"=>"Marshall Islands",
	"MS"=>"Mississippi",
	"MN"=>"Minnesota",
	"MO"=>"Missouri",
	"MT"=>"Montana",
	"NB"=>"New Brunswick",
	"NC"=>"North Carolina",
	"ND"=>"North Dakota",
	"NE"=>"Nebraska",
	"NV"=>"Nevada",
	"NF"=>"Newfoundland",
	"NH"=>"New Hampshire",
	"NJ"=>"New Jersey",
	"NM"=>"New Mexico",
	"NY"=>"New York",
	"OH"=>"Ohio",
	"OK"=>"Oklahoma",
	"ON"=>"Ontario",
	"OR"=>"Oregon",
	"PA"=>"Pennsylvania",
	"PE"=>"Prince Edward Island",
	"PR"=>"Puerto Ric",
	"PW"=>"Palau",
	"QC"=>"Quebec",
	"RI"=>"Rhode Island",
	"SC"=>"South Carolina",
	"SD"=>"South Dakota",
	"SK"=>"Saskatchewan",
	"TN"=>"Tenessee",
	"TX"=>"Texas",
	"UT"=>"Utah",
	"VA"=>"Virginia",
	"VI"=>"Virgin Islands",
	"VT"=>"Vermont",
	"WA"=>"Washington",
	"WV"=>"West Virginia",
	"WI"=>"Wisconsin",
	"WY"=>"Wyoming",
	"YT"=>"Yukon Territory",
	"ZZ"=>"Other Not Listed"
);

$utf_entities = array(
   chr(160) => "&nbsp;",
   chr(161) => "&iexcl;",
   chr(162) => "&cent;",
   chr(163) => "&pound;",
   chr(164) => "&curren;",
   chr(165) => "&yen;",
   chr(166) => "&brvbar;",
   chr(167) => "&sect;",
   chr(168) => "&uml;",
   chr(169) => "&copy;",
   chr(170) => "&ordf;",
   chr(171) => "&laquo;",
   chr(172) => "&not;",
   chr(173) => "&shy;",
   chr(174) => "&reg;",
   chr(175) => "&macr;",
   chr(176) => "&deg;",
   chr(177) => "&plusmn;",
   chr(178) => "&sup2;",
   chr(179) => "&sup3;",
   chr(180) => "&acute;",
   chr(181) => "&micro;",
   chr(182) => "&para;",
   chr(183) => "&middot;",
   chr(184) => "&cedil;",
   chr(185) => "&sup1;",
   chr(186) => "&ordm;",
   chr(187) => "&raquo;",
   chr(188) => "&frac14;",
   chr(189) => "&frac12;",
   chr(190) => "&frac34;",
   chr(191) => "&iquest;",
   chr(192) => "&Agrave;",
   chr(193) => "&Aacute;",
   chr(194) => "&Acirc;",
   chr(195) => "&Atilde;",
   chr(196) => "&Auml;",
   chr(197) => "&Aring;",
   chr(198) => "&AElig;",
   chr(199) => "&Ccedil;",
   chr(200) => "&Egrave;",
   chr(201) => "&Eacute;",
   chr(202) => "&Ecirc;",
   chr(203) => "&Euml;",
   chr(204) => "&Igrave;",
   chr(205) => "&Iacute;",
   chr(206) => "&Icirc;",
   chr(207) => "&Iuml;",
   chr(208) => "&ETH;",
   chr(209) => "&Ntilde;",
   chr(210) => "&Ograve;",
   chr(211) => "&Oacute;",
   chr(212) => "&Ocirc;",
   chr(213) => "&Otilde;",
   chr(214) => "&Ouml;",
   chr(215) => "&times;",
   chr(216) => "&Oslash;",
   chr(217) => "&Ugrave;",
   chr(218) => "&Uacute;",
   chr(219) => "&Ucirc;",
   chr(220) => "&Uuml;",
   chr(221) => "&Yacute;",
   chr(222) => "&THORN;",
   chr(223) => "&szlig;",
   chr(224) => "&agrave;",
   chr(225) => "&aacute;",
   chr(226) => "&acirc;",
   chr(227) => "&atilde;",
   chr(228) => "&auml;",
   chr(229) => "&aring;",
   chr(230) => "&aelig;",
   chr(231) => "&ccedil;",
   chr(232) => "&egrave;",
   chr(233) => "&eacute;",
   chr(234) => "&ecirc;",
   chr(235) => "&euml;",
   chr(236) => "&igrave;",
   chr(237) => "&iacute;",
   chr(238) => "&icirc;",
   chr(239) => "&iuml;",
   chr(240) => "&eth;",
   chr(241) => "&ntilde;",
   chr(242) => "&ograve;",
   chr(243) => "&oacute;",
   chr(244) => "&ocirc;",
   chr(245) => "&otilde;",
   chr(246) => "&ouml;",
   chr(247) => "&divide;",
   chr(248) => "&oslash;",
   chr(249) => "&ugrave;",
   chr(250) => "&uacute;",
   chr(251) => "&ucirc;",
   chr(252) => "&uuml;",
   chr(253) => "&yacute;",
   chr(254) => "&thorn;",
   chr(255) => "&yuml;",
   chr(8364) => "&euro;",
   chr(8482) => "&trade;",
);

$mime_types_map = array(
    '3dm' => 'x-world/x-3dmf', '3dmf' => 'x-world/x-3dmf', 'a' => 'application/octet-stream', 'aab' => 'application/x-authorware-bin',
    'aam' => 'application/x-authorware-map', 'aas' => 'application/x-authorware-seg', 'abc' => 'text/vnd.abc', 'acgi' => 'text/html',
    'afl' => 'video/animaflex', 'ai' => 'application/postscript', 'aif' => 'audio/aiff', 'aif' => 'audio/x-aiff',
    'aifc' => 'audio/aiff', 'aifc' => 'audio/x-aiff', 'aiff' => 'audio/aiff', 'aiff' => 'audio/x-aiff',
    'aim' => 'application/x-aim', 'aip' => 'text/x-audiosoft-intra', 'ani' => 'application/x-navi-animation', 'aos' => 'application/x-nokia-9000-communicator-add-on-software',
    'aps' => 'application/mime', 'arc' => 'application/octet-stream', 'arj' => 'application/arj', 'arj' => 'application/octet-stream',
    'art' => 'image/x-jg', 'asf' => 'video/x-ms-asf', 'asm' => 'text/x-asm', 'asp' => 'text/asp',
    'asx' => 'application/x-mplayer2', 'asx' => 'video/x-ms-asf', 'asx' => 'video/x-ms-asf-plugin', 'au' => 'audio/basic',
    'au' => 'audio/x-au', 'avi' => 'application/x-troff-msvideo', 'avi' => 'video/avi', 'avi' => 'video/msvideo',
    'avi' => 'video/x-msvideo', 'avs' => 'video/avs-video', 'bcpio' => 'application/x-bcpio', 'bin' => 'application/mac-binary',
    'bin' => 'application/macbinary', 'bin' => 'application/octet-stream', 'bin' => 'application/x-binary', 'bin' => 'application/x-macbinary',
    'bm' => 'image/bmp', 'bmp' => 'image/bmp', 'bmp' => 'image/x-windows-bmp', 'boo' => 'application/book',
    'book' => 'application/book', 'boz' => 'application/x-bzip2', 'bsh' => 'application/x-bsh', 'bz' => 'application/x-bzip',
    'bz2' => 'application/x-bzip2', 'c' => 'text/plain', 'c' => 'text/x-c', 'c++' => 'text/plain',
    'cat' => 'application/vnd.ms-pki.seccat', 'cc' => 'text/plain', 'cc' => 'text/x-c', 'ccad' => 'application/clariscad',
    'cco' => 'application/x-cocoa', 'cdf' => 'application/cdf', 'cdf' => 'application/x-cdf', 'cdf' => 'application/x-netcdf',
    'cer' => 'application/pkix-cert', 'cer' => 'application/x-x509-ca-cert', 'cha' => 'application/x-chat', 'chat' => 'application/x-chat',
    'class' => 'application/java', 'class' => 'application/java-byte-code', 'class' => 'application/x-java-class', 'com' => 'application/octet-stream',
    'com' => 'text/plain', 'conf' => 'text/plain', 'cpio' => 'application/x-cpio', 'cpp' => 'text/x-c',
    'cpt' => 'application/mac-compactpro', 'cpt' => 'application/x-compactpro', 'cpt' => 'application/x-cpt', 'crl' => 'application/pkcs-crl',
    'crl' => 'application/pkix-crl', 'crt' => 'application/pkix-cert', 'crt' => 'application/x-x509-ca-cert', 'crt' => 'application/x-x509-user-cert',
    'csh' => 'application/x-csh', 'csh' => 'text/x-script.csh', 'css' => 'application/x-pointplus', 'css' => 'text/css',
    'cxx' => 'text/plain', 'dcr' => 'application/x-director', 'deepv' => 'application/x-deepv', 'def' => 'text/plain',
    'der' => 'application/x-x509-ca-cert', 'dif' => 'video/x-dv', 'dir' => 'application/x-director', 'dl' => 'video/dl',
    'dl' => 'video/x-dl', 'doc' => 'application/msword', 'dot' => 'application/msword', 'dp' => 'application/commonground',
    'drw' => 'application/drafting', 'dump' => 'application/octet-stream', 'dv' => 'video/x-dv', 'dvi' => 'application/x-dvi',
    'dwf' => 'drawing/x-dwf', 'dwf' => 'model/vnd.dwf', 'dwg' => 'application/acad', 'dwg' => 'image/vnd.dwg',
    'dwg' => 'image/x-dwg', 'dxf' => 'application/dxf', 'dxf' => 'image/vnd.dwg', 'dxf' => 'image/x-dwg',
    'dxr' => 'application/x-director', 'el' => 'text/x-script.elisp', 'elc' => 'application/x-bytecode.elisp', 'elc' => 'application/x-elc',
    'env' => 'application/x-envoy', 'eps' => 'application/postscript', 'es' => 'application/x-esrehber', 'etx' => 'text/x-setext',
    'evy' => 'application/envoy', 'evy' => 'application/x-envoy', 'exe' => 'application/octet-stream', 'f' => 'text/plain',
    'f' => 'text/x-fortran', 'f77' => 'text/x-fortran', 'f90' => 'text/plain', 'f90' => 'text/x-fortran',
    'fdf' => 'application/vnd.fdf', 'fif' => 'application/fractals', 'fif' => 'image/fif', 'fli' => 'video/fli',
    'fli' => 'video/x-fli', 'flo' => 'image/florian', 'flx' => 'text/vnd.fmi.flexstor', 'fmf' => 'video/x-atomic3d-feature',
    'for' => 'text/plain', 'for' => 'text/x-fortran', 'fpx' => 'image/vnd.fpx', 'fpx' => 'image/vnd.net-fpx',
    'frl' => 'application/freeloader', 'funk' => 'audio/make', 'g' => 'text/plain', 'g3' => 'image/g3fax',
    'gif' => 'image/gif', 'gl' => 'video/gl', 'gl' => 'video/x-gl', 'gsd' => 'audio/x-gsm',
    'gsm' => 'audio/x-gsm', 'gsp' => 'application/x-gsp', 'gss' => 'application/x-gss', 'gtar' => 'application/x-gtar',
    'gz' => 'application/x-compressed', 'gz' => 'application/x-gzip', 'gzip' => 'application/x-gzip', 'gzip' => 'multipart/x-gzip',
    'h' => 'text/plain', 'h' => 'text/x-h', 'hdf' => 'application/x-hdf', 'help' => 'application/x-helpfile',
    'hgl' => 'application/vnd.hp-hpgl', 'hh' => 'text/plain', 'hh' => 'text/x-h', 'hlb' => 'text/x-script',
    'hlp' => 'application/hlp', 'hlp' => 'application/x-helpfile', 'hlp' => 'application/x-winhelp', 'hpg' => 'application/vnd.hp-hpgl',
    'hpgl' => 'application/vnd.hp-hpgl', 'hqx' => 'application/binhex', 'hqx' => 'application/binhex4', 'hqx' => 'application/mac-binhex',
    'hqx' => 'application/mac-binhex40', 'hqx' => 'application/x-binhex40', 'hqx' => 'application/x-mac-binhex40', 'hta' => 'application/hta',
    'htc' => 'text/x-component', 'htm' => 'text/html', 'html' => 'text/html', 'htmls' => 'text/html',
    'htt' => 'text/webviewhtml', 'htx' => 'text/html', 'ice' => 'x-conference/x-cooltalk', 'ico' => 'image/x-icon',
    'idc' => 'text/plain', 'ief' => 'image/ief', 'iefs' => 'image/ief', 'iges' => 'application/iges',
    'iges' => 'model/iges', 'igs' => 'application/iges', 'igs' => 'model/iges', 'ima' => 'application/x-ima',
    'imap' => 'application/x-httpd-imap', 'inf' => 'application/inf', 'ins' => 'application/x-internett-signup', 'ip' => 'application/x-ip2',
    'isu' => 'video/x-isvideo', 'it' => 'audio/it', 'iv' => 'application/x-inventor', 'ivr' => 'i-world/i-vrml',
    'ivy' => 'application/x-livescreen', 'jam' => 'audio/x-jam', 'jav' => 'text/plain', 'jav' => 'text/x-java-source',
    'java' => 'text/plain', 'java' => 'text/x-java-source', 'jcm' => 'application/x-java-commerce', 'jfif' => 'image/jpeg',
    'jfif' => 'image/pjpeg', 'jfif-tbnl' => 'image/jpeg', 'jpe' => 'image/jpeg', 'jpe' => 'image/pjpeg',
    'jpeg' => 'image/jpeg', 'jpeg' => 'image/pjpeg', 'jpg' => 'image/jpeg', 'jpg' => 'image/pjpeg',
    'jps' => 'image/x-jps', 'js' => 'application/x-javascript', 'jut' => 'image/jutvision', 'kar' => 'audio/midi',
    'kar' => 'music/x-karaoke', 'ksh' => 'application/x-ksh', 'ksh' => 'text/x-script.ksh', 'la' => 'audio/nspaudio',
    'la' => 'audio/x-nspaudio', 'lam' => 'audio/x-liveaudio', 'latex' => 'application/x-latex', 'lha' => 'application/lha',
    'lha' => 'application/octet-stream', 'lha' => 'application/x-lha', 'lhx' => 'application/octet-stream', 'list' => 'text/plain',
    'lma' => 'audio/nspaudio', 'lma' => 'audio/x-nspaudio', 'log' => 'text/plain', 'lsp' => 'application/x-lisp',
    'lsp' => 'text/x-script.lisp', 'lst' => 'text/plain', 'lsx' => 'text/x-la-asf', 'ltx' => 'application/x-latex',
    'lzh' => 'application/octet-stream', 'lzh' => 'application/x-lzh', 'lzx' => 'application/lzx', 'lzx' => 'application/octet-stream',
    'lzx' => 'application/x-lzx', 'm' => 'text/plain', 'm' => 'text/x-m', 'm1v' => 'video/mpeg',
    'm2a' => 'audio/mpeg', 'm2v' => 'video/mpeg', 'm3u' => 'audio/x-mpequrl', 'man' => 'application/x-troff-man',
    'map' => 'application/x-navimap', 'mar' => 'text/plain', 'mbd' => 'application/mbedlet', 'mc$' => 'application/x-magic-cap-package-1.0',
    'mcd' => 'application/mcad', 'mcd' => 'application/x-mathcad', 'mcf' => 'image/vasa', 'mcf' => 'text/mcf',
    'mcp' => 'application/netmc', 'me' => 'application/x-troff-me', 'mht' => 'message/rfc822', 'mhtml' => 'message/rfc822',
    'mid' => 'application/x-midi', 'mid' => 'audio/midi', 'mid' => 'audio/x-mid', 'mid' => 'audio/x-midi',
    'mid' => 'music/crescendo', 'mid' => 'x-music/x-midi', 'midi' => 'application/x-midi', 'midi' => 'audio/midi',
    'midi' => 'audio/x-mid', 'midi' => 'audio/x-midi', 'midi' => 'music/crescendo', 'midi' => 'x-music/x-midi',
    'mif' => 'application/x-frame', 'mif' => 'application/x-mif', 'mime' => 'message/rfc822', 'mime' => 'www/mime',
    'mjf' => 'audio/x-vnd.audioexplosion.mjuicemediafile', 'mjpg' => 'video/x-motion-jpeg', 'mm' => 'application/base64', 'mm' => 'application/x-meme',
    'mme' => 'application/base64', 'mod' => 'audio/mod', 'mod' => 'audio/x-mod', 'moov' => 'video/quicktime',
    'mov' => 'video/quicktime', 'movie' => 'video/x-sgi-movie', 'mp2' => 'audio/mpeg', 'mp2' => 'audio/x-mpeg',
    'mp2' => 'video/mpeg', 'mp2' => 'video/x-mpeg', 'mp2' => 'video/x-mpeq2a', 'mp3' => 'audio/mpeg3',
    'mp3' => 'audio/x-mpeg-3', 'mp3' => 'video/mpeg', 'mp3' => 'video/x-mpeg', 'mpa' => 'audio/mpeg',
    'mpa' => 'video/mpeg', 'mpc' => 'application/x-project', 'mpe' => 'video/mpeg', 'mpeg' => 'video/mpeg',
    'mpg' => 'audio/mpeg', 'mpg' => 'video/mpeg', 'mpga' => 'audio/mpeg', 'mpp' => 'application/vnd.ms-project',
    'mpt' => 'application/x-project', 'mpv' => 'application/x-project', 'mpx' => 'application/x-project', 'mrc' => 'application/marc',
    'ms' => 'application/x-troff-ms', 'mv' => 'video/x-sgi-movie', 'my' => 'audio/make', 'mzz' => 'application/x-vnd.audioexplosion.mzz',
    'nap' => 'image/naplps', 'naplps' => 'image/naplps', 'nc' => 'application/x-netcdf', 'ncm' => 'application/vnd.nokia.configuration-message',
    'nif' => 'image/x-niff', 'niff' => 'image/x-niff', 'nix' => 'application/x-mix-transfer', 'nsc' => 'application/x-conference',
    'nvd' => 'application/x-navidoc', 'o' => 'application/octet-stream', 'oda' => 'application/oda', 'omc' => 'application/x-omc',
    'omcd' => 'application/x-omcdatamaker', 'omcr' => 'application/x-omcregerator', 'p' => 'text/x-pascal', 'p10' => 'application/pkcs10',
    'p10' => 'application/x-pkcs10', 'p12' => 'application/pkcs-12', 'p12' => 'application/x-pkcs12', 'p7a' => 'application/x-pkcs7-signature',
    'p7c' => 'application/pkcs7-mime', 'p7c' => 'application/x-pkcs7-mime', 'p7m' => 'application/pkcs7-mime', 'p7m' => 'application/x-pkcs7-mime',
    'p7r' => 'application/x-pkcs7-certreqresp', 'p7s' => 'application/pkcs7-signature', 'part' => 'application/pro_eng', 'pas' => 'text/pascal',
    'pbm' => 'image/x-portable-bitmap', 'pcl' => 'application/vnd.hp-pcl', 'pcl' => 'application/x-pcl', 'pct' => 'image/x-pict',
    'pcx' => 'image/x-pcx', 'pdb' => 'chemical/x-pdb', 'pdf' => 'application/pdf', 'pfunk' => 'audio/make',
    'pfunk' => 'audio/make.my.funk', 'pgm' => 'image/x-portable-graymap', 'pgm' => 'image/x-portable-greymap', 'pic' => 'image/pict',
    'pict' => 'image/pict', 'pkg' => 'application/x-newton-compatible-pkg', 'pko' => 'application/vnd.ms-pki.pko', 'pl' => 'text/plain',
    'pl' => 'text/x-script.perl', 'plx' => 'application/x-pixclscript', 'pm' => 'image/x-xpixmap', 'pm' => 'text/x-script.perl-module',
    'pm4' => 'application/x-pagemaker', 'pm5' => 'application/x-pagemaker', 'png' => 'image/png', 'pnm' => 'application/x-portable-anymap',
    'pnm' => 'image/x-portable-anymap', 'pot' => 'application/mspowerpoint', 'pot' => 'application/vnd.ms-powerpoint', 'pov' => 'model/x-pov',
    'ppa' => 'application/vnd.ms-powerpoint', 'ppm' => 'image/x-portable-pixmap', 'pps' => 'application/mspowerpoint', 'pps' => 'application/vnd.ms-powerpoint',
    'ppt' => 'application/mspowerpoint', 'ppt' => 'application/powerpoint', 'ppt' => 'application/vnd.ms-powerpoint', 'ppt' => 'application/x-mspowerpoint',
    'ppz' => 'application/mspowerpoint', 'pre' => 'application/x-freelance', 'prt' => 'application/pro_eng', 'ps' => 'application/postscript',
    'psd' => 'application/octet-stream', 'pvu' => 'paleovu/x-pv', 'pwz' => 'application/vnd.ms-powerpoint', 'py' => 'text/x-script.phyton',
    'pyc' => 'applicaiton/x-bytecode.python', 'qcp' => 'audio/vnd.qcelp', 'qd3' => 'x-world/x-3dmf', 'qd3d' => 'x-world/x-3dmf',
    'qif' => 'image/x-quicktime', 'qt' => 'video/quicktime', 'qtc' => 'video/x-qtc', 'qti' => 'image/x-quicktime',
    'qtif' => 'image/x-quicktime', 'ra' => 'audio/x-pn-realaudio', 'ra' => 'audio/x-pn-realaudio-plugin', 'ra' => 'audio/x-realaudio',
    'ram' => 'audio/x-pn-realaudio', 'ras' => 'application/x-cmu-raster', 'ras' => 'image/cmu-raster', 'ras' => 'image/x-cmu-raster',
    'rast' => 'image/cmu-raster', 'rexx' => 'text/x-script.rexx', 'rf' => 'image/vnd.rn-realflash', 'rgb' => 'image/x-rgb',
    'rm' => 'application/vnd.rn-realmedia', 'rm' => 'audio/x-pn-realaudio', 'rmi' => 'audio/mid', 'rmm' => 'audio/x-pn-realaudio',
    'rmp' => 'audio/x-pn-realaudio', 'rmp' => 'audio/x-pn-realaudio-plugin', 'rng' => 'application/ringing-tones', 'rng' => 'application/vnd.nokia.ringing-tone',
    'rnx' => 'application/vnd.rn-realplayer', 'roff' => 'application/x-troff', 'rp' => 'image/vnd.rn-realpix', 'rpm' => 'audio/x-pn-realaudio-plugin',
    'rt' => 'text/richtext', 'rt' => 'text/vnd.rn-realtext', 'rtf' => 'application/rtf', 'rtf' => 'application/x-rtf',
    'rtf' => 'text/richtext', 'rtx' => 'application/rtf', 'rtx' => 'text/richtext', 'rv' => 'video/vnd.rn-realvideo',
    's' => 'text/x-asm', 's3m' => 'audio/s3m', 'saveme' => 'application/octet-stream', 'sbk' => 'application/x-tbook',
    'scm' => 'application/x-lotusscreencam', 'scm' => 'text/x-script.guile', 'scm' => 'text/x-script.scheme', 'scm' => 'video/x-scm',
    'sdml' => 'text/plain', 'sdp' => 'application/sdp', 'sdp' => 'application/x-sdp', 'sdr' => 'application/sounder',
    'sea' => 'application/sea', 'sea' => 'application/x-sea', 'set' => 'application/set', 'sgm' => 'text/sgml',
    'sgm' => 'text/x-sgml', 'sgml' => 'text/sgml', 'sgml' => 'text/x-sgml', 'sh' => 'application/x-bsh',
    'sh' => 'application/x-sh', 'sh' => 'application/x-shar', 'sh' => 'text/x-script.sh', 'shar' => 'application/x-bsh',
    'shar' => 'application/x-shar', 'shtml' => 'text/html', 'shtml' => 'text/x-server-parsed-html', 'sid' => 'audio/x-psid',
    'sit' => 'application/x-sit', 'sit' => 'application/x-stuffit', 'skd' => 'application/x-koan', 'skm' => 'application/x-koan',
    'skp' => 'application/x-koan', 'skt' => 'application/x-koan', 'sl' => 'application/x-seelogo', 'smi' => 'application/smil',
    'smil' => 'application/smil', 'snd' => 'audio/basic', 'snd' => 'audio/x-adpcm', 'sol' => 'application/solids',
    'spc' => 'application/x-pkcs7-certificates', 'spc' => 'text/x-speech', 'spl' => 'application/futuresplash', 'spr' => 'application/x-sprite',
    'sprite' => 'application/x-sprite', 'src' => 'application/x-wais-source', 'ssi' => 'text/x-server-parsed-html', 'ssm' => 'application/streamingmedia',
    'sst' => 'application/vnd.ms-pki.certstore', 'step' => 'application/step', 'stl' => 'application/sla', 'stl' => 'application/vnd.ms-pki.stl',
    'stl' => 'application/x-navistyle', 'stp' => 'application/step', 'sv4cpio' => 'application/x-sv4cpio', 'sv4crc' => 'application/x-sv4crc',
    'svf' => 'image/vnd.dwg', 'svf' => 'image/x-dwg', 'svr' => 'application/x-world', 'svr' => 'x-world/x-svr',
    'swf' => 'application/x-shockwave-flash', 't' => 'application/x-troff', 'talk' => 'text/x-speech', 'tar' => 'application/x-tar',
    'tbk' => 'application/toolbook', 'tbk' => 'application/x-tbook', 'tcl' => 'application/x-tcl', 'tcl' => 'text/x-script.tcl',
    'tcsh' => 'text/x-script.tcsh', 'tex' => 'application/x-tex', 'texi' => 'application/x-texinfo', 'texinfo' => 'application/x-texinfo',
    'text' => 'application/plain', 'text' => 'text/plain', 'tgz' => 'application/gnutar', 'tgz' => 'application/x-compressed',
    'tif' => 'image/tiff', 'tif' => 'image/x-tiff', 'tiff' => 'image/tiff', 'tiff' => 'image/x-tiff',
    'tr' => 'application/x-troff', 'tsi' => 'audio/tsp-audio', 'tsp' => 'application/dsptype', 'tsp' => 'audio/tsplayer',
    'tsv' => 'text/tab-separated-values', 'turbot' => 'image/florian', 'txt' => 'text/plain', 'uil' => 'text/x-uil',
    'uni' => 'text/uri-list', 'unis' => 'text/uri-list', 'unv' => 'application/i-deas', 'uri' => 'text/uri-list',
    'uris' => 'text/uri-list', 'ustar' => 'application/x-ustar', 'ustar' => 'multipart/x-ustar', 'uu' => 'application/octet-stream',
    'uu' => 'text/x-uuencode', 'uue' => 'text/x-uuencode', 'vcd' => 'application/x-cdlink', 'vcs' => 'text/x-vcalendar',
    'vda' => 'application/vda', 'vdo' => 'video/vdo', 'vew' => 'application/groupwise', 'viv' => 'video/vivo',
    'viv' => 'video/vnd.vivo', 'vivo' => 'video/vivo', 'vivo' => 'video/vnd.vivo', 'vmd' => 'application/vocaltec-media-desc',
    'vmf' => 'application/vocaltec-media-file', 'voc' => 'audio/voc', 'voc' => 'audio/x-voc', 'vos' => 'video/vosaic',
    'vox' => 'audio/voxware', 'vqe' => 'audio/x-twinvq-plugin', 'vqf' => 'audio/x-twinvq', 'vql' => 'audio/x-twinvq-plugin',
    'vrml' => 'application/x-vrml', 'vrml' => 'model/vrml', 'vrml' => 'x-world/x-vrml', 'vrt' => 'x-world/x-vrt',
    'vsd' => 'application/x-visio', 'vst' => 'application/x-visio', 'vsw' => 'application/x-visio', 'w60' => 'application/wordperfect6.0',
    'w61' => 'application/wordperfect6.1', 'w6w' => 'application/msword', 'wav' => 'audio/wav', 'wav' => 'audio/x-wav',
    'wb1' => 'application/x-qpro', 'wbmp' => 'image/vnd.wap.wbmp', 'web' => 'application/vnd.xara', 'wiz' => 'application/msword',
    'wk1' => 'application/x-123', 'wmf' => 'windows/metafile', 'wml' => 'text/vnd.wap.wml', 'wmlc' => 'application/vnd.wap.wmlc',
    'wmls' => 'text/vnd.wap.wmlscript', 'wmlsc' => 'application/vnd.wap.wmlscriptc', 'word' => 'application/msword', 'wp' => 'application/wordperfect',
    'wp5' => 'application/wordperfect', 'wp5' => 'application/wordperfect6.0', 'wp6' => 'application/wordperfect', 'wpd' => 'application/wordperfect',
    'wpd' => 'application/x-wpwin', 'wq1' => 'application/x-lotus', 'wri' => 'application/mswrite', 'wri' => 'application/x-wri',
    'wrl' => 'application/x-world', 'wrl' => 'model/vrml', 'wrl' => 'x-world/x-vrml', 'wrz' => 'model/vrml',
    'wrz' => 'x-world/x-vrml', 'wsc' => 'text/scriplet', 'wsrc' => 'application/x-wais-source', 'wtk' => 'application/x-wintalk',
    'xbm' => 'image/x-xbitmap', 'xbm' => 'image/x-xbm', 'xbm' => 'image/xbm', 'xdr' => 'video/x-amt-demorun',
    'xgz' => 'xgl/drawing', 'xif' => 'image/vnd.xiff', 'xl' => 'application/excel', 'xla' => 'application/excel',
    'xla' => 'application/x-excel', 'xla' => 'application/x-msexcel', 'xlb' => 'application/excel', 'xlb' => 'application/vnd.ms-excel',
    'xlb' => 'application/x-excel', 'xlc' => 'application/excel', 'xlc' => 'application/vnd.ms-excel', 'xlc' => 'application/x-excel',
    'xld' => 'application/excel', 'xld' => 'application/x-excel', 'xlk' => 'application/excel', 'xlk' => 'application/x-excel',
    'xll' => 'application/excel', 'xll' => 'application/vnd.ms-excel', 'xll' => 'application/x-excel', 'xlm' => 'application/excel',
    'xlm' => 'application/vnd.ms-excel', 'xlm' => 'application/x-excel', 'xls' => 'application/excel', 'xls' => 'application/vnd.ms-excel',
    'xls' => 'application/x-excel', 'xls' => 'application/x-msexcel', 'xlt' => 'application/excel', 'xlt' => 'application/x-excel',
    'xlv' => 'application/excel', 'xlv' => 'application/x-excel', 'xlw' => 'application/excel', 'xlw' => 'application/vnd.ms-excel',
    'xlw' => 'application/x-excel', 'xlw' => 'application/x-msexcel', 'xm' => 'audio/xm', 'xml' => 'application/xml',
    'xml' => 'text/xml', 'xmz' => 'xgl/movie', 'xpix' => 'application/x-vnd.ls-xpix', 'xpm' => 'image/x-xpixmap',
    'xpm' => 'image/xpm', 'x-png' => 'image/png', 'xsr' => 'video/x-amt-showrun', 'xwd' => 'image/x-xwd',
    'xwd' => 'image/x-xwindowdump', 'xyz' => 'chemical/x-pdb', 'z' => 'application/x-compress', 'z' => 'application/x-compressed',
    'zip' => 'application/x-compressed', 'zip' => 'application/x-zip-compressed', 'zip' => 'application/zip', 'zip' => 'multipart/x-zip',
    'zoo' => 'application/octet-stream', 'zsh' => 'text/x-script.zsh',
);

$word_list_1000 = array(
   "the",
   "of",
   "to",
   "and",
   "a",
   "in",
   "is",
   "it",
   "you",
   "that",
   "he",
   "was",
   "for",
   "on",
   "are",
   "with",
   "as",
   "I",
   "his",
   "they",
   "be",
   "at",
   "one",
   "have",
   "this",
   "from",
   "or",
   "had",
   "by",
   "hot",
   "word",
   "but",
   "what",
   "some",
   "we",
   "can",
   "out",
   "other",
   "were",
   "all",
   "there",
   "when",
   "up",
   "use",
   "your",
   "how",
   "said",
   "an",
   "each",
   "she",
   "which",
   "do",
   "their",
   "time",
   "if",
   "will",
   "way",
   "about",
   "many",
   "then",
   "them",
   "write",
   "would",
   "like",
   "so",
   "these",
   "her",
   "long",
   "make",
   "thing",
   "see",
   "him",
   "two",
   "has",
   "look",
   "more",
   "day",
   "could",
   "go",
   "come",
   "did",
   "number",
   "sound",
   "no",
   "most",
   "people",
   "my",
   "over",
   "know",
   "water",
   "than",
   "call",
   "first",
   "who",
   "may",
   "down",
   "side",
   "been",
   "now",
   "find",
   "any",
   "new",
   "work",
   "part",
   "take",
   "get",
   "place",
   "made",
   "live",
   "where",
   "after",
   "back",
   "little",
   "only",
   "round",
   "man",
   "year",
   "came",
   "show",
   "every",
   "good",
   "me",
   "give",
   "our",
   "under",
   "name",
   "very",
   "through",
   "just",
   "form",
   "sentence",
   "great",
   "think",
   "say",
   "help",
   "low",
   "line",
   "differ",
   "turn",
   "cause",
   "much",
   "mean",
   "before",
   "move",
   "right",
   "boy",
   "old",
   "too",
   "same",
   "tell",
   "does",
   "set",
   "three",
   "want",
   "air",
   "well",
   "also",
   "play",
   "small",
   "end",
   "put",
   "home",
   "read",
   "hand",
   "port",
   "large",
   "spell",
   "add",
   "even",
   "land",
   "here",
   "must",
   "big",
   "high",
   "such",
   "follow",
   "act",
   "why",
   "ask",
   "men",
   "change",
   "went",
   "light",
   "kind",
   "off",
   "need",
   "house",
   "picture",
   "try",
   "us",
   "again",
   "animal",
   "point",
   "mother",
   "world",
   "near",
   "build",
   "self",
   "earth",
   "father",
   "head",
   "stand",
   "own",
   "page",
   "should",
   "country",
   "found",
   "answer",
   "school",
   "grow",
   "study",
   "still",
   "learn",
   "plant",
   "cover",
   "food",
   "sun",
   "four",
   "between",
   "state",
   "keep",
   "eye",
   "never",
   "last",
   "let",
   "thought",
   "city",
   "tree",
   "cross",
   "farm",
   "hard",
   "start",
   "might",
   "story",
   "saw",
   "far",
   "sea",
   "draw",
   "left",
   "late",
   "run",
   "don't",
   "while",
   "press",
   "close",
   "night",
   "real",
   "life",
   "few",
   "north",
   "open",
   "seem",
   "together",
   "next",
   "white",
   "children",
   "begin",
   "got",
   "walk",
   "example",
   "ease",
   "paper",
   "group",
   "always",
   "music",
   "those",
   "both",
   "mark",
   "often",
   "letter",
   "until",
   "mile",
   "river",
   "car",
   "feet",
   "care",
   "second",
   "book",
   "carry",
   "took",
   "science",
   "eat",
   "room",
   "friend",
   "began",
   "idea",
   "fish",
   "mountain",
   "stop",
   "once",
   "base",
   "hear",
   "horse",
   "cut",
   "sure",
   "watch",
   "color",
   "face",
   "wood",
   "main",
   "enough",
   "plain",
   "girl",
   "usual",
   "young",
   "ready",
   "above",
   "ever",
   "red",
   "list",
   "though",
   "feel",
   "talk",
   "bird",
   "soon",
   "body",
   "dog",
   "family",
   "direct",
   "pose",
   "leave",
   "song",
   "measure",
   "door",
   "product",
   "black",
   "short",
   "numeral",
   "class",
   "wind",
   "question",
   "happen",
   "complete",
   "ship",
   "area",
   "half",
   "rock",
   "order",
   "fire",
   "south",
   "problem",
   "piece",
   "told",
   "knew",
   "pass",
   "since",
   "top",
   "whole",
   "king",
   "space",
   "heard",
   "best",
   "hour",
   "better",
   "true .",
   "during",
   "hundred",
   "five",
   "remember",
   "step",
   "early",
   "hold",
   "west",
   "ground",
   "interest",
   "reach",
   "fast",
   "verb",
   "sing",
   "listen",
   "six",
   "table",
   "travel",
   "less",
   "morning",
   "ten",
   "simple",
   "several",
   "vowel",
   "toward",
   "war",
   "lay",
   "against",
   "pattern",
   "slow",
   "center",
   "love",
   "person",
   "money",
   "serve",
   "appear",
   "road",
   "map",
   "rain",
   "rule",
   "govern",
   "pull",
   "cold",
   "notice",
   "voice",
   "unit",
   "power",
   "town",
   "fine",
   "certain",
   "fly",
   "fall",
   "lead",
   "cry",
   "dark",
   "machine",
   "note",
   "wait",
   "plan",
   "figure",
   "star",
   "box",
   "noun",
   "field",
   "rest",
   "correct",
   "able",
   "pound",
   "done",
   "beauty",
   "drive",
   "stood",
   "contain",
   "front",
   "teach",
   "week",
   "final",
   "gave",
   "green",
   "oh",
   "quick",
   "develop",
   "ocean",
   "warm",
   "free",
   "minute",
   "strong",
   "special",
   "mind",
   "behind",
   "clear",
   "tail",
   "produce",
   "fact",
   "street",
   "inch",
   "multiply",
   "nothing",
   "course",
   "stay",
   "wheel",
   "full",
   "force",
   "blue",
   "object",
   "decide",
   "surface",
   "deep",
   "moon",
   "island",
   "foot",
   "system",
   "busy",
   "test",
   "record",
   "boat",
   "common",
   "gold",
   "possible",
   "plane",
   "stead",
   "dry",
   "wonder",
   "laugh",
   "thousand",
   "ago",
   "ran",
   "check",
   "game",
   "shape",
   "equate",
   "miss",
   "brought",
   "heat",
   "snow",
   "tire",
   "bring",
   "yes",
   "distant",
   "fill",
   "east",
   "paint",
   "language",
   "among",
   "grand",
   "ball",
   "yet",
   "wave",
   "drop",
   "heart",
   "am",
   "present",
   "heavy",
   "dance",
   "engine",
   "position",
   "arm",
   "wide",
   "sail",
   "material",
   "size",
   "vary",
   "settle",
   "speak",
   "weight",
   "general",
   "ice",
   "matter",
   "circle",
   "pair",
   "include",
   "divide",
   "syllable",
   "felt",
   "perhaps",
   "pick",
   "sudden",
   "count",
   "square",
   "reason",
   "length",
   "represent",
   "art",
   "subject",
   "region",
   "energy",
   "hunt",
   "probable",
   "bed",
   "brother",
   "egg",
   "ride",
   "cell",
   "believe",
   "fraction",
   "forest",
   "sit",
   "race",
   "window",
   "store",
   "summer",
   "train",
   "sleep",
   "prove",
   "lone",
   "leg",
   "exercise",
   "wall",
   "catch",
   "mount",
   "wish",
   "sky",
   "board",
   "joy",
   "winter",
   "sat",
   "written",
   "wild",
   "instrument",
   "kept",
   "glass",
   "grass",
   "cow",
   "job",
   "edge",
   "sign",
   "visit",
   "past",
   "soft",
   "fun",
   "bright",
   "gas",
   "weather",
   "month",
   "million",
   "bear",
   "finish",
   "happy",
   "hope",
   "flower",
   "clothe",
   "strange",
   "gone",
   "jump",
   "baby",
   "eight",
   "village",
   "meet",
   "root",
   "buy",
   "raise",
   "solve",
   "metal",
   "whether",
   "push",
   "seven",
   "paragraph",
   "third",
   "shall",
   "held",
   "hair",
   "describe",
   "cook",
   "floor",
   "either",
   "result",
   "burn",
   "hill",
   "safe",
   "cat",
   "century",
   "consider",
   "type",
   "law",
   "bit",
   "coast",
   "copy",
   "phrase",
   "silent",
   "tall",
   "sand",
   "soil",
   "roll",
   "temperature",
   "finger",
   "industry",
   "value",
   "fight",
   "lie",
   "beat",
   "excite",
   "natural",
   "view",
   "sense",
   "ear",
   "else",
   "quite",
   "broke",
   "case",
   "middle",
   "kill",
   "son",
   "lake",
   "moment",
   "scale",
   "loud",
   "spring",
   "observe",
   "child",
   "straight",
   "consonant",
   "nation",
   "dictionary",
   "milk",
   "speed",
   "method",
   "organ",
   "pay",
   "age",
   "section",
   "dress",
   "cloud",
   "surprise",
   "quiet",
   "stone",
   "tiny",
   "climb",
   "cool",
   "design",
   "poor",
   "lot",
   "experiment",
   "bottom",
   "key",
   "iron",
   "single",
   "stick",
   "flat",
   "twenty",
   "skin",
   "smile",
   "crease",
   "hole",
   "trade",
   "melody",
   "trip",
   "office",
   "receive",
   "row",
   "mouth",
   "exact",
   "symbol",
   "die",
   "least",
   "trouble",
   "shout",
   "except",
   "wrote",
   "seed",
   "tone",
   "join",
   "suggest",
   "clean",
   "break",
   "lady",
   "yard",
   "rise",
   "bad",
   "blow",
   "oil",
   "blood",
   "touch",
   "grew",
   "cent",
   "mix",
   "team",
   "wire",
   "cost",
   "lost",
   "brown",
   "wear",
   "garden",
   "equal",
   "sent",
   "choose",
   "fell",
   "fit",
   "flow",
   "fair",
   "bank",
   "collect",
   "save",
   "control",
   "decimal",
   "gentle",
   "woman",
   "captain",
   "practice",
   "separate",
   "difficult",
   "doctor",
   "please",
   "protect",
   "noon",
   "whose",
   "locate",
   "ring",
   "character",
   "insect",
   "caught",
   "period",
   "indicate",
   "radio",
   "spoke",
   "atom",
   "human",
   "history",
   "effect",
   "electric",
   "expect",
   "crop",
   "modern",
   "element",
   "hit",
   "student",
   "corner",
   "party",
   "supply",
   "bone",
   "rail",
   "imagine",
   "provide",
   "agree",
   "thus",
   "capital",
   "won't",
   "chair",
   "danger",
   "fruit",
   "rich",
   "thick",
   "soldier",
   "process",
   "operate",
   "guess",
   "necessary",
   "sharp",
   "wing",
   "create",
   "neighbor",
   "wash",
   "bat",
   "rather",
   "crowd",
   "corn",
   "compare",
   "poem",
   "string",
   "bell",
   "depend",
   "meat",
   "rub",
   "tube",
   "famous",
   "dollar",
   "stream",
   "fear",
   "sight",
   "thin",
   "triangle",
   "planet",
   "hurry",
   "chief",
   "colony",
   "clock",
   "mine",
   "tie",
   "enter",
   "major",
   "fresh",
   "search",
   "send",
   "yellow",
   "gun",
   "allow",
   "print",
   "dead",
   "spot",
   "desert",
   "suit",
   "current",
   "lift",
   "rose",
   "continue",
   "block",
   "chart",
   "hat",
   "sell",
   "success",
   "company",
   "subtract",
   "event",
   "particular",
   "deal",
   "swim",
   "term",
   "opposite",
   "wife",
   "shoe",
   "shoulder",
   "spread",
   "arrange",
   "camp",
   "invent",
   "cotton",
   "born",
   "determine",
   "quart",
   "nine",
   "truck",
   "noise",
   "level",
   "chance",
   "gather",
   "shop",
   "stretch",
   "throw",
   "shine",
   "property",
   "column",
   "molecule",
   "select",
   "wrong",
   "gray",
   "repeat",
   "require",
   "broad",
   "prepare",
   "salt",
   "nose",
   "plural",
   "anger",
   "claim",
   "continent",
   "oxygen",
   "sugar",
   "death",
   "pretty",
   "skill",
   "women",
   "season",
   "solution",
   "magnet",
   "silver",
   "thank",
   "branch",
   "match",
   "suffix",
   "especially",
   "fig",
   "afraid",
   "huge",
   "sister",
   "steel",
   "discuss",
   "forward",
   "similar",
   "guide",
   "experience",
   "score",
   "apple",
   "bought",
   "led",
   "pitch",
   "coat",
   "mass",
   "card",
   "band",
   "rope",
   "slip",
   "win",
   "dream",
   "evening",
   "condition",
   "feed",
   "tool",
   "]total",
   "basic",
   "smell",
   "valley",
   "nor",
   "double",
   "seat",
   "arrive",
   "master",
   "track",
   "parent",
   "shore",
   "division",
   "sheet",
   "substance",
   "favor",
   "connect",
   "post",
   "spend",
   "chord",
   "fat",
   "glad",
   "original",
   "share",
   "station",
   "dad",
   "bread",
   "charge",
   "proper",
   "bar",
   "offer",
   "segment",
   "slave",
   "duck",
   "instant",
   "market",
   "degree",
   "populate",
   "chick",
   "dear",
   "enemy",
   "reply",
   "drink",
   "occur",
   "support",
   "speech",
   "nature",
   "range",
   "steam",
   "motion",
   "path",
   "liquid",
   "log",
   "meant",
   "quotient",
   "teeth",
   "shell",
   "neck",
);

$word_list_100 = array(
   "a",
   "able",
   "about",
   "across",
   "after",
   "all",
   "almost",
   "also",
   "am",
   "among",
   "an", 
   "and", 
   "any", 
   "are", 
   "as", 
   "at", 
   "be", 
   "because", 
   "been", 
   "but", 
   "by", 
   "can", 
   "cannot", 
   "could",
   "dear", 
   "did", 
   "do", 
   "does", 
   "either", 
   "else", 
   "ever", 
   "every", 
   "for",
   "from", 
   "get", 
   "got", 
   "had", 
   "has", 
   "have", 
   "he", 
   "her", 
   "hers", 
   "him", 
   "his", 
   "how", 
   "however", 
   "i", 
   "if", 
   "in",
   "into", 
   "is", 
   "it", 
   "its", 
   "just", 
   "least", 
   "let", 
   "like", 
   "likely", 
   "may",
   "me", 
   "might", 
   "most", 
   "must", 
   "my", 
   "neither", 
   "no", 
   "nor", 
   "not", 
   "of", 
   "off", 
   "often", 
   "on",
   "only", 
   "or", 
   "other", 
   "our", 
   "own", 
   "rather", 
   "said", 
   "say", 
   "says", 
   "she", 
   "should", 
   "since", 
   "so", 
   "some",
   "than", 
   "that",  
   "the",  
   "their", 
   "them", 
   "then", 
   "there", 
   "these", 
   "they",
   "this", 
   "tis", 
   "to", 
   "too", 
   "twas", 
   "us", 
   "wants", 
   "was", 
   "we", 
   "were", 
   "what", 
   "when", 
   "where", 
   "which",
   "while", 
   "who", 
   "whom", 
   "why", 
   "will", 
   "with", 
   "would", 
   "yet", 
   "you",  
   "your",
);


?>
