CREATE TABLE `page` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `clientid` int(10) unsigned default NULL,
  `deleted` int(10) unsigned default '0',
  `userlist` int(10) unsigned default '0',
  `create_date` datetime NOT NULL default '0000-00-00 00:00:00',
  `crawl_date` datetime NOT NULL default '0000-00-00 00:00:00',
  `last_modified_date` datetime NOT NULL default '0000-00-00 00:00:00',
  `flags` text,
  `url` text,
  `page` mediumtext,
  `language` text,
  `name` text,
  `username` text,
  `listname` text,
  `meta` mediumtext,
  `img` mediumtext,
  `title` text,
  `pagetext` mediumtext,
  `condensed` mediumtext,
  PRIMARY KEY  (`id`),
  KEY `clientid_index` (`clientid`),
  KEY `title_index` (`title`(333)),
  KEY `url_index` (`url`(333)),
  KEY `meta_index` (`meta`(333)),
  KEY `name_index` (`name`(333)),
  KEY `page_index` (`page`(333)),
  KEY `language_index` (`language`(333)),
  KEY `pagetext_index` (`pagetext`(333)),
  KEY `cond_index` (`condensed`(333)),
  FULLTEXT KEY `pagesearch` (`page`),
  FULLTEXT KEY `textsearch` (`pagetext`),
  FULLTEXT KEY `titlesearch` (`title`),
  FULLTEXT KEY `namesearch` (`name`),
  FULLTEXT KEY `condsearch` (`condensed`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

